language: erlang
sudo: false
install: wget https://s3.amazonaws.com/rebar3/rebar3 && chmod 755 rebar3
script: PATH=.:$PATH make check-all
notifications:
  email: false
otp_release:
  - 18.2.1
  - 18.1
  - 18.0
  - 17.5
  - 17.4
  - 17.3
  - 17.1
  - 17.0
